// Curated real government schemes — health, housing, women, seniors, social security.
export default [
  {
    code: 'PMJAY', name: 'Ayushman Bharat PM-JAY', type: 'health',
    category: 'Health', desc: 'Health cover of Rs.5 lakh per family per year for secondary and tertiary hospitalisation for eligible families.',
    amt: [0, 500000], rate: 0, sub: 100, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 300000, age: [0, 120], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], universal: true, prefer_bpl: true },
    docs: ['Aadhaar', 'Ration Card', 'Income Certificate'],
    url: 'https://www.myscheme.gov.in/schemes/ayushman-bharat-pm-jay', ministry: 'Ministry of Health and Family Welfare', portal: 'NHA',
  },
  {
    code: 'JANAUSHADHI', name: 'PM Bharatiya Janaushadhi Pariyojana', type: 'health',
    category: 'Health', desc: 'Quality generic medicines at affordable prices through Janaushadhi Kendras across the country.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [0, 120], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Prescription'],
    url: 'https://www.myscheme.gov.in/schemes/janaushadhi', ministry: 'Ministry of Chemicals and Fertilizers', portal: 'PMBJP',
  },
  {
    code: 'JSY', name: 'Janani Suraksha Yojana', type: 'health',
    category: 'Women', desc: 'Cash assistance to pregnant women for institutional delivery to reduce maternal and neonatal mortality.',
    amt: [0, 1400], rate: 0, sub: 100, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 300000, age: [18, 49], gender: 'female', occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], prefer_bpl: true },
    docs: ['Aadhaar', 'MCP Card', 'Bank Passbook', 'BPL Card'],
    url: 'https://www.myscheme.gov.in/schemes/janani-suraksha-yojana', ministry: 'Ministry of Health and Family Welfare', portal: 'NHM',
  },
  {
    code: 'PMSMA', name: 'Pradhan Mantri Surakshit Matritva Abhiyan', type: 'health',
    category: 'Women', desc: 'Free comprehensive antenatal check-ups for pregnant women on the 9th of every month at government facilities.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [18, 49], gender: 'female', occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [] },
    docs: ['Aadhaar', 'MCP Card'],
    url: 'https://www.myscheme.gov.in/schemes/pmsma', ministry: 'Ministry of Health and Family Welfare', portal: 'NHM',
  },
  {
    code: 'NIKSHAY-POSHAN', name: 'Nikshay Poshan Yojana', type: 'health',
    category: 'Health', desc: 'Direct benefit transfer of Rs.1,000 per month to tuberculosis patients to support nutritional needs during treatment.',
    amt: [0, 12000], rate: 0, sub: 100, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [0, 120], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Bank Passbook', 'TB Treatment Record'],
    url: 'https://www.myscheme.gov.in/schemes/nikshay-poshan-yojana', ministry: 'Ministry of Health and Family Welfare', portal: 'Nikshay',
  },
  {
    code: 'PMNDP', name: 'PM National Dialysis Programme', type: 'health',
    category: 'Health', desc: 'Free dialysis services for poor patients at district hospitals through public-private partnership.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 300000, age: [0, 120], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], prefer_bpl: true },
    docs: ['Aadhaar', 'Income Certificate', 'Medical Records'],
    url: 'https://www.myscheme.gov.in/schemes/pm-national-dialysis-programme', ministry: 'Ministry of Health and Family Welfare', portal: 'NHM',
  },
  {
    code: 'ESIC', name: 'Employees State Insurance Scheme', type: 'health',
    category: 'Health', desc: 'Comprehensive medical care and cash benefits for insured workers and their dependants under the ESI Act.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [16, 65], occ: ['salaried', 'business'], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [] },
    docs: ['Aadhaar', 'Employer Certificate', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/esic', ministry: 'Ministry of Labour and Employment', portal: 'ESIC',
  },
  {
    code: 'PMAY-G', name: 'Pradhan Mantri Awas Yojana - Gramin', type: 'housing_loan',
    category: 'Housing', desc: 'Financial assistance to build a pucca house with basic amenities for rural households without a dwelling.',
    amt: [0, 180000], rate: 0, sub: 100, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 300000, age: [18, 70], occ: [], purpose: ['housing'], area: ['rural'], cats: [], states: [], universal: true, prefer_bpl: true },
    docs: ['Aadhaar', 'Ration Card', 'Income Certificate', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/pmay-g', ministry: 'Ministry of Rural Development', portal: 'PMAY-G',
  },
  {
    code: 'PMAY-U', name: 'Pradhan Mantri Awas Yojana - Urban', type: 'housing_loan',
    category: 'Housing', desc: 'Housing support for urban beneficiaries through in-situ slum redevelopment, affordable housing and interest subsidy.',
    amt: [0, 267000], rate: 0, sub: 100, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 1800000, age: [18, 70], occ: [], purpose: ['housing'], area: ['urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Income Certificate', 'Bank Passbook', 'Address Proof'],
    url: 'https://www.myscheme.gov.in/schemes/pmay-u', ministry: 'Ministry of Housing and Urban Affairs', portal: 'PMAY-U',
  },
  {
    code: 'CLSS', name: 'Credit Linked Subsidy Scheme (Housing)', type: 'housing_loan',
    category: 'Housing', desc: 'Interest subsidy on home loans for EWS, LIG and MIG households under PMAY-Urban.',
    amt: [0, 1200000], rate: 8.5, sub: 6.5, margin: 10, ten: [60, 240], mor: 0,
    rules: { income: 1800000, age: [21, 70], occ: [], purpose: ['housing'], area: ['urban'], cats: [], states: [] },
    docs: ['Aadhaar', 'Income Certificate', 'Property Documents', 'Bank Statement'],
    url: 'https://www.myscheme.gov.in/schemes/clss', ministry: 'Ministry of Housing and Urban Affairs', portal: 'PMAY-U',
  },
  {
    code: 'ARHC', name: 'Affordable Rental Housing Complexes', type: 'housing_loan',
    category: 'Housing', desc: 'Rental housing for urban migrants and poor through conversion of vacant government housing into ARHCs.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 600000, age: [18, 70], occ: [], purpose: ['housing'], area: ['urban'], cats: [], states: [] },
    docs: ['Aadhaar', 'Employment Proof', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/arhc', ministry: 'Ministry of Housing and Urban Affairs', portal: 'ARHC',
  },
  {
    code: 'PMMVY', name: 'Pradhan Mantri Matru Vandana Yojana', type: 'health',
    category: 'Women', desc: 'Maternity benefit of Rs.5,000 for the first living child to compensate for wage loss and support nutrition.',
    amt: [0, 5000], rate: 0, sub: 100, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 800000, age: [18, 49], gender: 'female', occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [] },
    docs: ['Aadhaar', 'MCP Card', 'Bank Passbook', 'Husband Aadhaar'],
    url: 'https://www.myscheme.gov.in/schemes/pmmvy', ministry: 'Ministry of Women and Child Development', portal: 'PMMVY',
  },
  {
    code: 'BBB-P', name: 'Beti Bachao Beti Padhao', type: 'subsidy',
    category: 'Women', desc: 'National campaign to improve the child sex ratio, ensure survival, protection and education of the girl child.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [0, 18], gender: 'female', occ: [], purpose: ['education'], area: ['rural', 'urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Birth Certificate'],
    url: 'https://www.myscheme.gov.in/schemes/beti-bachao-beti-padhao', ministry: 'Ministry of Women and Child Development', portal: 'WCD',
  },
  {
    code: 'MAHILA-SHAKTI', name: 'Mahila Shakti Kendra', type: 'skill',
    category: 'Women', desc: 'Convergence centres at block level providing skill development, employment and digital literacy support to rural women.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 500000, age: [18, 60], gender: 'female', occ: ['looking', 'business'], purpose: ['education'], area: ['rural'], cats: [], states: [] },
    docs: ['Aadhaar', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/mahila-shakti-kendra', ministry: 'Ministry of Women and Child Development', portal: 'WCD',
  },
  {
    code: 'ONE-STOP-CENTRE', name: 'One Stop Centre Scheme', type: 'health',
    category: 'Women', desc: 'Integrated support and assistance to women affected by violence, including police, medical and legal aid under one roof.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [0, 120], gender: 'female', occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Complaint Details'],
    url: 'https://www.myscheme.gov.in/schemes/one-stop-centre', ministry: 'Ministry of Women and Child Development', portal: 'WCD',
  },
  {
    code: 'SWADHAR-GREH', name: 'SWADHAR Greh', type: 'health',
    category: 'Women', desc: 'Temporary shelter, food, clothing and health care for women in distress including those without social support.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 300000, age: [18, 65], gender: 'female', occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [] },
    docs: ['Aadhaar', 'Referral Details'],
    url: 'https://www.myscheme.gov.in/schemes/swadhar-greh', ministry: 'Ministry of Women and Child Development', portal: 'WCD',
  },
  {
    code: 'WORKING-WOMEN-HOSTEL', name: 'Working Women Hostel', type: 'housing_loan',
    category: 'Women', desc: 'Safe and affordable hostel accommodation for working women and single women with day-care facilities for children.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [18, 65], gender: 'female', occ: ['salaried', 'business', 'artisan'], purpose: ['housing'], area: ['urban'], cats: [], states: [] },
    docs: ['Aadhaar', 'Employment Proof', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/working-women-hostel', ministry: 'Ministry of Women and Child Development', portal: 'WCD',
  },
  {
    code: 'ATAL-VAYO', name: 'Atal Vayo Abhyuday Yojana', type: 'pension',
    category: 'Senior Citizens', desc: 'Welfare of senior citizens through shelter, health care, awareness, and support to old age homes and Vayoshri centres.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 400000, age: [60, 120], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Age Proof', 'Income Certificate'],
    url: 'https://www.myscheme.gov.in/schemes/atal-vayo-abhyuday-yojana', ministry: 'Ministry of Social Justice and Empowerment', portal: 'AVYAY',
  },
  {
    code: 'VAYOSHRI', name: 'Rashtriya Vayoshri Yojana', type: 'subsidy',
    category: 'Senior Citizens', desc: 'Distribution of physical aids and assisted-living devices free of cost to senior citizens from BPL families.',
    amt: [0, 0], rate: 0, sub: 100, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 300000, age: [60, 120], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], prefer_bpl: true },
    docs: ['Aadhaar', 'Age Proof', 'BPL Card'],
    url: 'https://www.myscheme.gov.in/schemes/rashtriya-vayoshri-yojana', ministry: 'Ministry of Social Justice and Empowerment', portal: 'ALIMCO',
  },
  {
    code: 'NSAP-OAPS', name: 'Indira Gandhi National Old Age Pension (NSAP)', type: 'pension',
    category: 'Senior Citizens', desc: 'Monthly pension to persons aged 60+ belonging to below poverty line households under the NSAP.',
    amt: [0, 24000], rate: 0, sub: 100, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 300000, age: [60, 120], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], universal: true, prefer_bpl: true },
    docs: ['Aadhaar', 'Age Proof', 'BPL Card', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/indira-gandhi-national-old-age-pension', ministry: 'Ministry of Rural Development', portal: 'NSAP',
  },
  {
    code: 'NSAP-IGNDPS', name: 'Indira Gandhi National Disability Pension Scheme', type: 'pension',
    category: 'Social Security', desc: 'Monthly pension to persons with severe or multiple disabilities aged 18-79 from BPL households.',
    amt: [0, 24000], rate: 0, sub: 100, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: 300000, age: [18, 79], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [], universal: true, prefer_bpl: true, disability: true },
    docs: ['Aadhaar', 'Disability Certificate', 'BPL Card', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/indira-gandhi-national-disability-pension', ministry: 'Ministry of Rural Development', portal: 'NSAP',
  },
  {
    code: 'SCWF', name: 'Senior Citizens Welfare Fund', type: 'pension',
    category: 'Senior Citizens', desc: 'Funds welfare projects for senior citizens such as awareness, health care, and capacity building of caregivers.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [60, 120], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [] },
    docs: ['Aadhaar', 'Age Proof'],
    url: 'https://www.myscheme.gov.in/schemes/senior-citizens-welfare-fund', ministry: 'Ministry of Social Justice and Empowerment', portal: 'SCWF',
  },
  {
    code: 'VPBY', name: 'Varishtha Pension Bima Yojana', type: 'pension',
    category: 'Senior Citizens', desc: 'Pension scheme for citizens aged 60+ guaranteeing a assured rate of return on lump-sum subscription.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [60, 120], occ: [], purpose: ['health'], area: ['rural', 'urban'], cats: [], states: [] },
    docs: ['Aadhaar', 'Age Proof', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/varishtha-pension-bima-yojana', ministry: 'Ministry of Finance', portal: 'LIC',
  },
  {
    code: 'PMJJBY', name: 'PM Jeevan Jyoti Bima Yojana', type: 'social_security',
    category: 'Social Security', desc: 'Life insurance cover of Rs.2 lakh at a nominal annual premium for bank account holders aged 18-50.',
    amt: [0, 200000], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [18, 50], occ: [], purpose: ['business'], area: ['rural', 'urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/pmjjby', ministry: 'Ministry of Finance', portal: 'PMJJBY',
  },
  {
    code: 'PMSBY', name: 'PM Suraksha Bima Yojana', type: 'social_security',
    category: 'Social Security', desc: 'Accidental death and disability insurance cover of Rs.2 lakh at a nominal annual premium for ages 18-70.',
    amt: [0, 200000], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [18, 70], occ: [], purpose: ['business'], area: ['rural', 'urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Bank Passbook'],
    url: 'https://www.myscheme.gov.in/schemes/pmsby', ministry: 'Ministry of Finance', portal: 'PMSBY',
  },
  {
    code: 'APY', name: 'Atal Pension Yojana', type: 'pension',
    category: 'Social Security', desc: 'Guaranteed minimum pension of Rs.1,000-5,000 per month after 60 for subscribers aged 18-40.',
    amt: [0, 0], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [18, 40], occ: ['business', 'salaried', 'farmer', 'artisan', 'looking'], purpose: ['business'], area: ['rural', 'urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Bank Passbook', 'Mobile Number'],
    url: 'https://www.myscheme.gov.in/schemes/atal-pension-yojana', ministry: 'Ministry of Finance', portal: 'PFRDA',
  },
  {
    code: 'PMJDY', name: 'Pradhan Mantri Jan Dhan Yojana', type: 'social_security',
    category: 'Social Security', desc: 'Universal access to banking with zero-balance accounts, RuPay card, overdraft and accident insurance.',
    amt: [0, 10000], rate: 0, sub: 0, margin: 0, ten: [0, 0], mor: 0,
    rules: { income: null, age: [10, 120], occ: [], purpose: ['business'], area: ['rural', 'urban'], cats: [], states: [], universal: true },
    docs: ['Aadhaar', 'Photo'],
    url: 'https://www.myscheme.gov.in/schemes/pmjdy', ministry: 'Ministry of Finance', portal: 'PMJDY',
  },
];
